name: nfc_card_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: any
  hive: any
  hive_flutter: any
  nfc_manager: any
  path_provider: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
